"use client";
import { useEffect, useState } from "react";

const useMounted = () => {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return mounted;
};
export default useMounted;

/*
 * ===========================================================================================
 *                              NOTES — useMounted.tsx
 * ===========================================================================================
 *
 * PURPOSE: A custom React hook to determine if a component has mounted on the client-side.
 * ROLE IN ARCHITECTURE: Frontend Hooks Layer. Fixes Hydration mismatch errors in Next.js.
 * 
 * IMPORTS:
 * - `useEffect, useState`: React primitives.
 * 
 * FUNCTION-BY-FUNCTION ANALYSIS:
 * - `useMounted()`
 *   - Does: Initializes state as `false`. Uses `useEffect` (which only runs on the client, never during SSR) to flip the state to `true`.
 *   - Returns: A boolean (`true` if mounted on client, `false` during SSR).
 * 
 * HOW THIS FILE CONNECTS TO OTHER FILES:
 * - Inbound: Used by components that access browser-only APIs (like `localStorage` or `window`) or render randomly generated data to prevent React hydration errors.
 * 
 * DESIGN PATTERNS:
 * - Hydration Bypass Pattern: A common Next.js pattern to delay the rendering of client-specific UI until after the initial HTML is hydrated.
 * 
 * POTENTIAL INTERVIEW QUESTIONS:
 * 1. What exactly is a "hydration mismatch" and how does this hook prevent it?
 *    - Answer: Hydration mismatch occurs when the HTML generated by the server does not exactly match the initial HTML rendered by the client's React instance. If a component relies on `localStorage` (which the server can't read), the outputs will differ and React throws an error. This hook forces the component to render a consistent server state (`mounted = false`) and only updates to the client state after hydration completes.
 */